main: eu.octanne.mi5agent.Mi5AgentBukkit
authors: [Octanne]
version: 1.0
name: Mi5-Agent
description: Moderation Plugin with sanction history...
commands:
  tempban:
    description: Tempory Ban a player.
    aliases: [tban]
  ban:
    description: Finally Ban a player.
  tempmute:
    description: Tempory Mute a player.
    aliases: [tmute]
  mute:
    description: Finally Mute a player.
  unmute:
    description: Unmute a player.
  unban:
    description: Unban a player.
  warn:
    description: Warn a player.
  phistory:
    description: Open menu history for a player.
  vanish:
    description: Vanish command.
  freeze:
    description: Freeze command.
  kick:
    description: Kick command.